"""Model card generated from ``reports/metrics.json`` (FR-22). No number here is typed by hand."""

from __future__ import annotations

from typing import Any


def _f(x: float, nd: int = 4) -> str:
    return f"{x:.{nd}f}"


def render_model_card(metrics: dict[str, Any]) -> str:
    """Markdown model card covering intended use, data, method, results, limitations and ethics."""
    lines = [
        "# Model card: CreaseIQ win-probability models",
        "",
        "_Generated by `creaseiq train` from `reports/metrics.json`._",
        "",
        "## Intended use",
        "- Educational, pre-match estimates of the probability that one IPL franchise beats another, with explanations.",
        "- **Not for betting or any financial decision.** The estimates are close to a coin flip by design of the sport, and the model card below says so plainly.",
        "",
        "## Data",
        f"- Cricsheet-derived IPL match file (SHA-256 `{metrics['data_sha256'][:16]}…`), decided matches only (ties and no-results excluded).",
        f"- Development seasons ≤ {metrics['splits']['dev_last_season']} (walk-forward from {metrics['splits']['first_validation_season']}); **holdout {', '.join(map(str, metrics['splits']['holdout_seasons']))}**, evaluated once per frozen selection (see `reports/holdout_ledger.json`).",
        "",
        "## Method",
        f"- Features are computed as of the day before each match (date batches). Orientation is a hash-seeded coin flip, and predictions are symmetrised. Elo tuned on development folds: `{metrics['elo_tuning']['best']}`.",
        "- Tiers: **pre-toss** (history only) and **post-toss** (adds toss, batting order and the named XI).",
        "- Families compared: elo-logit, logistic regression (no intercept, antisymmetric features), random forest, histogram gradient boosting, and a blend. Selection uses the one-standard-error rule on walk-forward log-loss. Calibration (none, Platt or isotonic) is chosen in time order.",
        "",
        "## Results",
    ]
    for tier, t in metrics["tiers"].items():
        h = t["holdout"]["model"]
        ci = h["ci"]
        lines += [
            f"### {tier}",
            f"- Chosen: **{t['selection']['chosen']}** `{t['selection']['params']}`; calibration **{t['calibration']['chosen']}**; walk-forward log-loss {_f(t['selection']['walk_forward_mean_log_loss'])} ± {_f(t['selection']['walk_forward_std_log_loss'])} (coin flip 0.6931).",
            f"- Holdout (n = {h['n']}): log-loss **{_f(h['log_loss'])}** (95% CI {_f(ci['log_loss']['low'])}–{_f(ci['log_loss']['high'])}), Brier {_f(h['brier'])}, accuracy {h['accuracy']:.1%} (CI {ci['accuracy']['low']:.1%}–{ci['accuracy']['high']:.1%}), AUC {_f(h['auc'], 3)} (CI {_f(ci['auc']['low'], 3)}–{_f(ci['auc']['high'], 3)}), ECE {_f(h['ece'], 3)}.",
            "- Paired bootstrap against baselines (negative = model better): "
            + "; ".join(
                f"{k}: Δ={_f(v['diff'])} [{_f(v['ci_low'])}, {_f(v['ci_high'])}]"
                for k, v in t["holdout_vs_baselines"].items()
            )
            + ".",
            f"- Leakage guard ('too good' check): {'**SUSPICIOUS**' if t['too_good_guard']['suspicious'] else 'passed'}.",
            "",
        ]
    sr = metrics["score_regression"]
    lines += [
        "### First-innings score regression (P1)",
        f"- Holdout MAE: ridge {sr['holdout']['ridge']['mae']:.1f}, gradient boosting {sr['holdout']['hist_gb']['mae']:.1f}, recent-league-mean baseline {sr['holdout']['baseline_recent_league_mean']['mae']:.1f}, venue-level baseline {sr['holdout']['baseline_venue_level']['mae']:.1f} runs.",
        "",
        "## Limitations",
        "- Small n (about 1.2k decided matches; the holdout has about 140), so confidence intervals are wide. Differences of a few thousandths of log-loss are not meaningful.",
        "- Structural breaks: the Impact Player rule (2023), mega-auctions, relocated and neutral seasons. Relationships learned before 2023 (home advantage, rating persistence) weakened or reversed in the holdout years.",
        "- Unmodelled: player availability and injuries, pitch and dew, weather, individual form, ball-by-ball dynamics.",
        "- Franchise continuity assumptions (ADR-003). Some D/L results in 2010, 2012 and 2013 may be unflagged. Player identity is exact-string only.",
        "",
        "## Ethical considerations",
        "- Outputs must not be used for betting (Promotion and Regulation of Online Gaming Act, 2025) or to judge individuals.",
        "- The model predicts team outcomes only. It uses no personal data beyond public match records.",
    ]
    return "\n".join(lines) + "\n"
