"""Headline analytics written to ``reports/analytics.json`` (FR-22).

The report and README quote these numbers through templates. None are typed by hand.
"""

from __future__ import annotations

from typing import Any

import pandas as pd

from creaseiq.analytics import (
    player_stats,
    season_trends,
    team_stats,
    toss_analysis,
    venue_clusters,
    venue_stats,
)


def _pct(x: float) -> str:
    return f"{100 * x:.1f}%"


def render_findings_markdown(s: dict[str, Any]) -> str:
    """Plain-language findings with effect sizes and CIs (``docs/analytics_findings.md``)."""
    toss, chase, home, era = (
        s["toss"]["overall"],
        s["chasing"]["overall"],
        s["home_advantage"],
        s["era_scoring"],
    )
    toss_era, chase_era = (
        s["toss"]["era_test_impact_minus_pre"],
        s["chasing"]["era_test_impact_minus_pre"],
    )
    chi = s["toss"]["decision_outcome_chi2_associational"]
    dec = {r["toss_decision"]: r for r in s["toss"]["by_decision"]}
    top = s["teams"][0]
    lines = [
        "# Analytics findings",
        "",
        "_Generated by `creaseiq analyze` from `reports/analytics.json`. Numbers are never typed by hand._",
        "",
        "## 1. Winning the toss (causal test: the toss is random)",
        f"- Toss winners won **{_pct(toss['rate'])}** of {toss['n']} decided matches (95% Wilson CI {_pct(toss['ci_low'])}–{_pct(toss['ci_high'])}; exact binomial p = {toss['p_value']:.2f}).",
        f"- Effect vs a fair coin: {100 * toss['effect']:+.1f} pp. With n = {toss['n']} the minimum detectable effect (80% power) is ±{100 * toss['mde']:.1f} pp, so the data **rule out toss advantages larger than about {100 * max(abs(toss['ci_low'] - 0.5), abs(toss['ci_high'] - 0.5)):.0f} pp** but cannot distinguish a small one from zero. This agrees with Sood & Willis (2016) for T20.",
        f"- The effect did not change measurably in the Impact Player era (difference {100 * toss_era['diff']:+.1f} pp, 95% CI {100 * toss_era['ci_low']:+.1f} to {100 * toss_era['ci_high']:+.1f} pp, p = {toss_era['p_value']:.2f}).",
        "",
        "## 2. Batting second (chasing)",
        f"- The chasing side won **{_pct(chase['rate'])}** (95% CI {_pct(chase['ci_low'])}–{_pct(chase['ci_high'])}; p = {chase['p_value']:.3f}). This is a real, modest advantage.",
        f"- Impact era minus earlier seasons: {100 * chase_era['diff']:+.1f} pp (95% CI {100 * chase_era['ci_low']:+.1f} to {100 * chase_era['ci_high']:+.1f} pp, p = {chase_era['p_value']:.2f}). There is no evidence that the chasing edge grew.",
        f"- *Associational:* toss winners who chose to field won {_pct(dec['field']['rate'])} vs {_pct(dec['bat']['rate'])} for those who batted (χ² p = {chi['p_value']:.3f}, Cramér's V = {chi['cramers_v']:.2f}). The decision depends on conditions and team strength, so this gap is **not** a causal effect of choosing to field.",
        "",
        "## 3. Home advantage",
        f"- Where exactly one side was at home (neutral seasons excluded), the home side won {_pct(home['rate'])} of {home['n']} matches (95% CI {_pct(home['ci_low'])}–{_pct(home['ci_high'])}; p = {home['p_value']:.3f}). The effect is small and borderline.",
        "",
        "## 4. The Impact Player era changed scoring",
        f"- Mean first-innings score rose from {era['mean_pre']:.1f} to **{era['mean_post']:.1f}** (+{era['diff']:.1f} runs, 95% CI {era['ci_low']:.1f}–{era['ci_high']:.1f}; Welch p = {era['welch_p']:.1e}; Cohen's d = {era['cohens_d']:.2f}, a large effect).",
        f"- 200+ first innings: {_pct(era['share_200_pre'])} before 2023 vs **{_pct(era['share_200_post'])}** since.",
        "- Implication for modelling: scoring features must be era-aware (an `impact_era` flag plus rolling windows).",
        "",
        "## 5. Teams and venues",
        f"- Most successful franchise by titles and win rate: **{top['team']}** ({top['titles']} titles, win rate {_pct(top['win_pct'])}).",
        f"- k-means on shrunk venue profiles picked k = {s['venue_clusters']['k']} (silhouette {max(s['venue_clusters']['silhouette_by_k'].values()):.2f}); clusters: "
        + "; ".join(f"{c['label']}" for c in s["venue_clusters"]["centroids"])
        + ".",
    ]  # fmt: skip
    return "\n".join(lines) + "\n"


def _records(df: pd.DataFrame) -> list[dict[str, Any]]:
    return df.to_dict(orient="records")


def build_analytics_summary(
    m: pd.DataFrame, players: pd.DataFrame, seed: int = 42
) -> dict[str, Any]:
    """Compute every headline analytic in one place."""
    toss = toss_analysis.toss_effect(m)
    chase = toss_analysis.chasing_advantage(m)
    profiles = venue_stats.venue_profiles(m)
    clusters = venue_clusters.cluster_venues(profiles, seed=seed)
    teams = team_stats.team_table(m)
    return {
        "toss": {
            "overall": toss["overall"],
            "by_decision": _records(toss["by_decision"]),
            "by_era": _records(toss["by_era"]),
            "era_test_impact_minus_pre": toss["era_test_impact_minus_pre"],
            "decision_outcome_chi2_associational": toss["decision_outcome_chi2_associational"],
            "by_venue": _records(toss_analysis.toss_by_venue(m)),
        },
        "chasing": {
            "overall": chase["overall"],
            "era_test_impact_minus_pre": chase["era_test_impact_minus_pre"],
            "by_season": _records(chase["by_season"]),
        },
        "field_first_share": _records(toss_analysis.field_first_share(m)),
        "home_advantage": team_stats.home_advantage(m)["overall"],
        "home_by_season": _records(team_stats.home_advantage(m)["by_season"]),
        "teams": _records(teams),
        "scoring_by_season": _records(season_trends.scoring_by_season(m)),
        "era_scoring": season_trends.era_scoring_test(m),
        "venues_top": _records(profiles.head(12)),
        "venue_clusters": {
            "k": clusters.k,
            "silhouette_by_k": clusters.silhouette_by_k,
            "centroids": _records(clusters.centroids),
            "assignments": _records(clusters.assignments),
        },
        "potm_top": _records(player_stats.potm_leaderboard(m, players, 10)),
        "appearances_top": _records(player_stats.appearances(players, m, 10)),
    }
